Exclude tests folder from code coverage. Ignore errors caused by installing cargo-travis.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -39,11 +39,13 @@ matrix:
           cargo build &&
           travis_wait 30 cargo test &&
           cargo bench
-
+# TODO: Because caching when installing cargo-travis there can already exists one which fails because cargo install is stupid.
+# -f could be used to force installation, but that kinda defeats the point of caching,
+# so we just ignore error for now and just cross fingers and hope that there exists cargo-travis.
 before_script:
   - |
       cargo install cargo-travis &&
-      export PATH=$HOME/.cargo/bin:$PATH
+      export PATH=$HOME/.cargo/bin:$PATH || true
 
 after_success:
-  - cargo coveralls
+  - cargo coveralls --exclude-pattern tests/
